### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by malitha22** [dennisabrams/teamspeak3-banner#1]
Error Code: 0 php_network_getaddresses: getaddrinfo failed: Name or service not known

need help with this!
thanks

**Comment by dennisabrams** [comment]
Hey @malitha22,
thank you for pointing out the syntax errors.

It looks like DNS isn't working properly on your machine if you typed the name of your TS3 server inside the config.php (line 17) `$server_ip = "127.0.0.1";`
Did you try to put the IP address of your TS3 server instead?

**Comment by malitha22** [comment]
yes! I tried 127.0.0.1/localhost/ts3ip/domain

**Comment by malitha22** [comment]
but it didnt work

**Comment by dennisabrams** [comment]
The problem is that the API can't connect to your TS3 Server Query. 

> Check if port 10011 is open in your firewall.

You can check if your server query accepts TCP connections with this small program:
```php
<?php
$host = "YOUR TS3 SERVER IP"; 
$port = 10011; 
$waitTimeoutInSeconds = 1; 
if($fp = fsockopen($host,$port,$errCode,$errStr,$waitTimeoutInSeconds)){   
   echo("Online"); // Can create a connection
} else {
   echo("Offline"); // Can't create a connection
} 
fclose($fp);
?>
```

**Comment by malitha22** [comment]
@dennisabrams its online!

**Comment by malitha22** [comment]
@dennisabrams I tried with different vps and teamspeak servers but didnt work!

**Comment by dennisabrams** [comment]
```php
<?php
require_once("libraries/TeamSpeak3/TeamSpeak3.php"); // Your TS3 PHP framework path

$serverquery_username = "serveradmin";
$serverquery_password = "PASSWORD";
$server_ip = "127.0.0.1";
$serverquery_port = "10011";
$server_port = "9987";

try
{
  
  $conn = "serverquery://$serverquery_username:$serverquery_password@$server_ip:$serverquery_port/?server_port=$server_port";
  $ts3_VirtualServer = TeamSpeak3::factory($conn);
  echo($ts3_VirtualServer);
}
catch(TeamSpeak3_Exception $e)
{
  echo "Error Code:" . $e->getCode() . ": " . $e->getMessage();
}
?>
```
**Note:** Check if there are any special signs (special characters like: !@#$%^&*()_+:) inside the serverquery password!
⚠️TS3 PHP Framework doesn't like special characters at all! If you use it and don't want to change your password ~ use [rawurlencode][specialchar].


So if you tried this and it still fails, check the [Teamspeak 3 PHP Framework Docs][docs] and the informations & requirements inside the [README.md][readme].

> If your server is using an IPv6 adress it must be written within square brackets: `$conn = "serverquery://username:password@[fe80::250:56ff:fe16:1447]:10011/";`



[docs]: https://docs.planetteamspeak.com/ts3/php/framework/index.html
[readme]: https://github.com/planetteamspeak/ts3phpframework
[specialchar]: https://www.php.net/manual/en/function.rawurlencode.php

**Comment by malitha22** [comment]
thankyou so much! , the problem was the serverquery password its start with "@"

**Comment by dennisabrams** [comment]
No problem, I'm glad I could help 😊. I will add this problem to the [README.md][readme] and update the program soon, because I'm not completly finished yet 😅.

[readme]: https://github.com/dennisabrams/teamspeak3-banner/blob/main/README.md

**Comment by dennisabrams** [comment]
Special characters can be used inside the serverquery username & password now.
> Username & password will be encoded to RFC 3986 by default.
