### ISSUE TITLE
need help too

### ISSUE THREAD

**Issue by NemesorZahndrekhh** [dennisabrams/teamspeak3-banner#14]
hello, i installed it like your git, pre req. all already installed and config.php all filled in

change 127.0.0.1 to my ts3 ip and to localhost

i made the test.php which you gave to mathild in a issue before

it says Online

than i tried this

```
<?php
require_once("../vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php"); // Your TS3 PHP framework path


$serverquery_username = "serveradmin";
$serverquery_password = "password";
$server_ip = "server ip";
$serverquery_port = "10011";
$server_port = "9987";

try
{ 
  $conn = "serverquery://$serverquery_username:$serverquery_password@$server_ip:$serverquery_port/?server_port=$server_port";
  $ts3_VirtualServer = TeamSpeak3::factory($conn);
  echo($ts3_VirtualServer);
}
catch(TeamSpeak3_Exception $e)
{
  echo "Error Code:" . $e->getCode() . ": " . $e->getMessage();
}
?>
```

and i get the same result as the ts3-banner.php  - HTTP 500 Error, problem is i just don't know from where this problem comes? from ts3 banner? from ts3-php-framework? apache server itself? php?

maybe you know more

my problem is, that if i want to mydomain.com/ts3-banner/ts3-banner.php

**Comment by NemesorZahndrekhh** [comment]
<img width="524" alt="http 500 error" src="https://github.com/dennisabrams/teamspeak-banner/assets/95324815/dbfe65b7-db12-4b0d-b9b6-8b51c505b293">

**Comment by TOminerTV** [comment]
Hello, you can add the following debug code to the `ts3-banner.php`. If you then load the page in your browser you should see an error log. Please add this error log for more help to this thread.

```
error_reporting(E_ALL);
ini_set('display_errors', 'On');
```

**Comment by NemesorZahndrekhh** [comment]
ah ok - it seems the php cannot access to ../vendor/...  for ts3-php-framework inside var/html

```
Warning: require_once(root/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php): failed to open stream: No such file or directory in /var/www/html/ts3-banner/ts3-banner.php on line 16

Fatal error: require_once(): Failed opening required 'root/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php' (include_path='.:/usr/share/php') in /var/www/html/ts3-banner/ts3-banner.php on line 16
```

what i need to do? change folder chmod rights?

**Comment by TOminerTV** [comment]
I think it depends on where your files are stored. The "require_once"-path must match the "No such file or directory in"-path.

I think your problem is that you use the wrong path. Check line `12` in the `config.php`.
A possible solution could be the following file structure:

Base: /var/www/html
|--> vendor
|--> teamspeak-banner *files* (only the content of the downloaded repository)

Finally you have to change line `12` in the `config.php` to `$ts3_libary = './vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php';`
If the html folder is your root directory you can also use the following path for line `12`:
`/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php`

**Comment by NemesorZahndrekhh** [comment]
my old file structure is the following:

`./../root/vendor/plantteamspeak/ts3-php-framework/libraries/Teamspeak3/Teamspeak3.php`

`./../var/www/html/ts3-banner`

my approach was there 

`$ts3_libary = './root/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php'`
so after this does not go

i changed to what you said

`./../var/www/html/vendor/planetteamspeak/ts3-php-framework/libraries/Teamspeak3/Teamspeak3.php
`
`./../var/www/hmtl/ts3-banner`

my approach here like you said:

`$ts3_libary = './vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php'`

so now i get this - is this because it does not go either and it cannot read the ts3 php framework either? i guess it is


```
Notice: Undefined variable: connected_time in /var/www/html/ts3-banner/ts3-banner.php on line 76

Notice: Undefined variable: connected_time in /var/www/html/ts3-banner/ts3-banner.php on line 77

Notice: Undefined variable: last_time in /var/www/html/ts3-banner/ts3-banner.php on line 83

Warning: min(): When only one parameter is given, it must be an array in /var/www/html/ts3-banner/ts3-banner.php on line 83

Notice: Undefined variable: last_time in /var/www/html/ts3-banner/ts3-banner.php on line 83

Warning: array_search() expects parameter 2 to be array, null given in /var/www/html/ts3-banner/ts3-banner.php on line 83

Notice: Undefined variable: last_user in /var/www/html/ts3-banner/ts3-banner.php on line 83

Notice: Trying to access array offset on value of type null in /var/www/html/ts3-banner/ts3-banner.php on line 83

Notice: Undefined variable: last_time in /var/www/html/ts3-banner/ts3-banner.php on line 84

Warning: min(): When only one parameter is given, it must be an array in /var/www/html/ts3-banner/ts3-banner.php on line 84

Notice: Undefined variable: spacer in /var/www/html/ts3-banner/ts3-banner.php on line 86

Notice: Undefined variable: client in /var/www/html/ts3-banner/ts3-banner.php on line 89

Fatal error: Uncaught Error: Call to undefined function imagecreatefromstring() in /var/www/html/ts3-banner/ts3-banner.php:94 Stack trace: #0 {main} thrown in /var/www/html/ts3-banner/ts3-banner.php on line 94
```

**Comment by dennisabrams** [comment]
Hello, it seems your PHP installation might be missing the [GD library](https://www.php.net/manual/en/book.image.php) which is needed for handling images. Typically the [GD library](https://www.php.net/manual/en/book.image.php) is enabled by default in most PHP setups.

## Steps to Fix

### 1. Check if GD is installed
**Create a new PHP file with the following content:**
```php
<?php phpinfo(); ?>
```
Open this file in your web browser and search for "gd".
  
### 2. Install GD:
**For Ubuntu:**
```bash
sudo apt-get install php-gd
```
### 3. Restart your Web Server:

#### For Apache:
```bash
sudo service apache2 restart
```
#### For Nginx:
```bash
sudo service nginx restart
```


## Alternative Method
### Enabling GD in `php.ini`:

1. **Locate your `php.ini` file**. The location varies based on your setup:
   - **Linux (with Apache or standalone PHP)**: `/etc/php/[version]/cli/php.ini` for CLI and `/etc/php/[version]/apache2/php.ini` for Apache.
   - **Linux (with Nginx)**: Often at `/etc/php/[version]/fpm/php.ini`.
   
   If unsure, create a PHP file with `<?php phpinfo(); ?>`, load it in a browser, and look for "Loaded Configuration File" to see the exact path.

2. Open the located `php.ini` file in a text editor.
3. Search for a line containing `extension=gd` or `extension=gd2`.
4. If the line starts with a semicolon (`;`), it means GD is commented out (disabled). Remove the semicolon to enable it.
5. Save the `php.ini` file.
6. Restart your web server to apply the changes.

**Comment by NemesorZahndrekhh** [comment]
ok 👍 now its working thank you very much!

btw yes, you  where right, gd wasnt installed - installed it and it works
