### ISSUE TITLE
request features

### ISSUE THREAD

**Issue by malitha22** [dennisabrams/teamspeak3-banner#2]
first of all thank you for releasing this awesome banner script !
can you add more features like show server groups in banner and tsn ranksystem sync (ex - ts3server://flosing.de)

thanks!

**Comment by dennisabrams** [comment]
Hey @malitha22,
Unfortunately I don't have any time today but I'll add server groups tomorrow :). Tsn ranksystem is something new for me but I'll check it out too.

I'm glad that you liked my banner script <3

**Comment by malitha22** [comment]
thanks <3

**Comment by dennisabrams** [comment]
You can enable Server Group Icons inside the [`config.php`][config] now.
```php
$groups = 0; // 1 = Enabled, 0 = Disabled
```
You can check the [README.md][readme] inside the new [`server_groups`][groupicon] folder for more informations.

[readme]: https://github.com/dennisabrams/teamspeak3-banner/tree/main/server_groups#readme
[groupicon]: https://github.com/dennisabrams/teamspeak3-banner/tree/main/server_groups
[config]: https://github.com/dennisabrams/teamspeak3-banner/blob/main/config.php

**Comment by malitha22** [comment]
thank you so much! 
thanks for adding that feature so quick <3
here is my banner - https://cwresports.lk/banner/

**Comment by dennisabrams** [comment]
Wow! It looks awesome! 🤩 
Background rotation is a nice detail too. 
I might add this as an optional feature inside the [`config.php`](https://github.com/dennisabrams/teamspeak3-banner/blob/main/config.php). 😊

**Comment by malitha22** [comment]
Damn nice 😛, please let me know when you are add some features later!

**Comment by dennisabrams** [comment]
Hey @malitha22 
A new release is out: https://github.com/dennisabrams/teamspeak3-banner/releases/tag/v1.0.4
The Banner **without** any configuration inside the [`config.php`](https://github.com/dennisabrams/teamspeak3-banner/blob/main/config.php) will look like this now:
![github_banner](https://user-images.githubusercontent.com/122950707/224430899-411df284-b18a-4d13-bd12-df1de7d2c131.png)

**Comment by malitha22** [comment]
damn its better and better everytimee!

**Comment by malitha22** [comment]
thanks!

**Comment by malitha22** [comment]
request! @dennisabrams 
can you add a better date like this!
![224430742-36806f09-6181-44d4-95d7-147288f5eae4](https://user-images.githubusercontent.com/54675941/224451680-fe15a18c-0e35-4a4c-a832-2e1cdc90f3bf.png)

**Comment by dennisabrams** [comment]
Alright! New release is out: https://github.com/dennisabrams/teamspeak3-banner/releases/tag/v1.0.5
Because not everyone likes textually date there will be still an option to choose numerically date. 😊

**Comment by malitha22** [comment]
this quick? damn thankyou! 
its perfect now!

**Comment by dennisabrams** [comment]
Haha yea that quick, I had some free time today 😇.
Thank you! I would appreciate a Star ⭐ if you don't mind so more people can see my project. ❤️

**Comment by NemesorZahndrekhh** [comment]
> thank you so much! thanks for adding that feature so quick <3 here is my banner - https://cwresports.lk/banner/ ( I also added background rotation) ts ip - cwresports.lk
> 
> ![download (4)](https://user-images.githubusercontent.com/54675941/222988013-57f3e293-8487-4231-96fe-11aaf57617c4.jpeg)

hey, sorry to open this again (never did, so i don't know if i open it), but is there a chance that you share your approach to banner rotation? :)
