### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by HoRiiZeN** [dennisabrams/teamspeak3-banner#3]
I followed the instructions but i'm unable to change text color i changed the rgb value in the config.php tho.
and I specified the logo path but the banner's showing server name instead of logo.

![SW](https://user-images.githubusercontent.com/118933455/222873929-146325b0-cada-449d-8fd6-c30e09bba64d.PNG)

**Comment by dennisabrams** [comment]
Hello @HoRiiZeN,
Unfortunately I don't have any time today but I'll update my code tomorrow. ✌️

**Comment by HoRiiZeN** [comment]
> 

Alright, thanks 💖

**Comment by dennisabrams** [comment]
Colors & logo implementation are working now. You can change the RGB values inside the `config.php`.
```php
$text_color1 = array("R" => 255, "G" => 255, "B" => 255); // Custom text color RGB (0 - 255)
```

**Comment by dennisabrams** [comment]
A new release is out: https://github.com/dennisabrams/teamspeak3-banner/releases/tag/v1.0.4
The logo image transparency is fixed and you can add transparency to your text now. 👻

**Comment by HoRiiZeN** [comment]
Okay, thanks for the updates everything looks fine now except the informations, they're not showing for some reason :/ idk if it's my IP but it's just doesn't work for me :( .
I'd be appreciated if
![image](https://user-images.githubusercontent.com/118933455/224518309-c3d28d65-d5b9-4475-b0f4-84dc7ffbe3e2.png)

**Comment by HoRiiZeN** [comment]
THANKS for the update! everything's better now, I just have this problem where the "client info"  doesn't show up. I'm not using a Proxy/VPN. Is there anything you can do? I'd be appreciated if u helped me out 🥰
![image](https://user-images.githubusercontent.com/118933455/224518444-2bb9bcfa-9b81-4b14-9b09-bc6bfe02143e.png)

**Comment by HoRiiZeN** [comment]
THANKS for the update! everything's better now, I just have this problem where the "client info"  doesn't show up. I'm not using a Proxy/VPN. Is there anything you can do? I'd be appreciated if u helped me out 🥰
![image](https://user-images.githubusercontent.com/118933455/224518609-adccaab3-37d4-4595-bcce-4fdfa7cf3877.png)

**Comment by dennisabrams** [comment]
Hm.. 🤔 looks like there is a problem inside the _IP checking process_.
I updated it inside the [`ts3-banner.php`](https://github.com/dennisabrams/teamspeak3-banner/blob/main/ts3-banner.php) file [here](https://github.com/dennisabrams/teamspeak3-banner/commit/301752ed39759804ca22d1822d2f6042d84e82cf).
```php
<?php
echo $_SERVER['REMOTE_ADDR'];
?>
```
Check if this represents your real IP address.

**Comment by HoRiiZeN** [comment]
Amazing work 👏, now it's working just fine 💖
![image](https://user-images.githubusercontent.com/118933455/224595372-212e07ce-1241-4600-9183-aca35a0e5661.png)
